name: Dependency updates

on:
  schedule:
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Check dependency updates
        run: ./gradlew dependencyUpdates -D revision=release

      - name: Save dependency updates report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-updates-report.txt
          path: build/dependencyUpdates/report.txt
          retention-days: 1
